### ISSUE TITLE
We need to agree on row and column direction

### ISSUE THREAD

**Issue by kyleaig** [Carterahart18/CheckMate#12]
````
    	Official chess board layout is this:
    	| 7 . . . . . .
    	v 6	      .
    	  .	      .
	  .           .
	  .           .
	  0 1 2 3 . . 7
	  -->
		 
        Our board array looks like this:
	| 0 1 2 3 . . 7
    	v 1	      .
    	  .	      .
	  .           .
	  .           .
	  . . . . . . .
          -->
````

I think for move logic it would be better to stick to the official chess board layout, and then for accessing chess pieces for drawing maybe have some formula for converting the number in the official layout to the number in the board array. Let me know what ya think

![alt text](http://kidchess.com/new/wp-content/uploads/2016/06/kid-chess-setup-board.gif)

**Comment by Carterahart18** [comment]
I'll fix it
